version: '3.1'
services:
  stats-server:
    build: ./stats
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine

  ewm-service:
    build: ./ewm
    environment:
      - STATS-SERVER_URL=http://stats-server:9090
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
