server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm
    username: test
    password: test
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml