server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

app:
  minMinutesToEvent: 120
  name: ewm-main-service
  format:
    date-time: yyyy-MM-dd HH:mm:ss
  base-url:
    event: /events

stats-server:
  url: http://localhost:9090
  getPath: /stats
  postPath: /hit